 ## Importing Libraries

In [14]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns 

## Data Preprocessing

### Training Image Preprocessing

In [15]:
## link: keras.io/api/data_loading/image/
training_set=tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical", #we are use categorical here because of here we are dealing with more than two class problem
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


### Validation image preprocessing


In [16]:
## link: keras.io/api/data_loading/image/
validation_set=tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [17]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [18]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[207.75 206.75 214.75]
   [201.   200.   208.  ]
   [196.5  195.5  203.5 ]
   ...
   [167.75 170.75 185.75]
   [174.   177.   192.  ]
   [165.   171.   187.  ]]

  [[199.   198.   206.  ]
   [198.   197.   205.  ]
   [196.5  195.5  203.5 ]
   ...
   [164.   167.   182.  ]
   [164.   167.   182.  ]
   [158.25 161.25 178.25]]

  [[205.25 204.25 212.25]
   [203.75 202.75 210.75]
   [209.75 208.75 216.75]
   ...
   [163.25 165.25 180.25]
   [157.5  160.5  175.5 ]
   [163.   166.   181.  ]]

  ...

  [[181.5  175.5  187.5 ]
   [164.75 158.75 170.75]
   [178.   172.   184.  ]
   ...
   [124.75 120.75 134.75]
   [140.5  136.5  150.5 ]
   [145.   141.   155.  ]]

  [[205.75 199.75 211.75]
   [148.5  142.5  154.5 ]
   [161.25 155.25 167.25]
   ...
   [142.   138.   152.  ]
   [132.75 128.75 142.75]
   [137.25 133.25 147.25]]

  [[143.75 137.75 149.75]
   [142.25 136.25 148.25]
   [138.75 132.75 144.75]
   ...
   [167.   163.   177.  ]
   [146.25 142.25 156.25]
   [139.25 135.25 14