 ## Importing Libraries

In [131]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns 

## Data Preprocessing

### Training Image Preprocessing

In [132]:
## link: keras.io/api/data_loading/image/
training_set=tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical", #we are use categorical here because of here we are dealing with more than two class problem
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


### Validation image preprocessing


In [133]:
## link: keras.io/api/data_loading/image/
validation_set=tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [134]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [135]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 63.25  60.25  69.25]
   [ 62.25  59.25  68.25]
   [ 63.25  60.25  69.25]
   ...
   [115.75 133.75 117.75]
   [127.   145.   129.  ]
   [119.5  137.5  121.5 ]]

  [[ 64.    61.    70.  ]
   [ 63.5   60.5   69.5 ]
   [ 65.    62.    71.  ]
   ...
   [122.25 140.25 124.25]
   [122.75 140.75 124.75]
   [125.25 143.25 127.25]]

  [[ 66.5   63.5   72.5 ]
   [ 66.5   63.5   72.5 ]
   [ 69.    66.    75.  ]
   ...
   [124.75 142.75 126.75]
   [127.25 145.25 129.25]
   [122.25 140.25 124.25]]

  ...

  [[ 87.    84.    91.  ]
   [ 85.    82.    89.  ]
   [ 87.    84.    91.  ]
   ...
   [116.   142.   117.  ]
   [117.25 142.25 120.25]
   [120.25 145.25 123.25]]

  [[ 87.5   84.5   91.5 ]
   [ 85.5   82.5   89.5 ]
   [ 86.    83.    90.  ]
   ...
   [115.75 140.75 118.75]
   [117.   142.   120.  ]
   [115.   140.   118.  ]]

  [[ 88.5   85.5   92.5 ]
   [ 85.75  82.75  89.75]
   [ 86.    83.    90.  ]
   ...
   [115.5  140.5  118.5 ]
   [114.75 139.75 117.75]
   [115.5  140.5  11

### To avoid Overshooting
1. Choose small learning rate, default 0.001 we are taking 0.0001
2. There may be chance of Underfitting. So increase Number of neurons
3. Add more Convolution layer to extract more feature from images. There may be possibility that model unable to capture relevant feature or model is confusing due to lack of feature. So feed with more feature

## Building model

In [136]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential


In [137]:
model=Sequential()

In [138]:
## Building convolutional Layer

In [139]:
model.add(Conv2D(filters=32,kernel_size=3,padding="same",activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

c:\Users\Gopal Sharma\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [140]:
model.add(Conv2D(filters=64,kernel_size=3,padding="same",activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [141]:
model.add(Conv2D(filters=128,kernel_size=3,padding="same",activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [142]:
model.add(Conv2D(filters=256,kernel_size=3,padding="same",activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [143]:
model.add(Conv2D(filters=512,kernel_size=3,padding="same",activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [144]:
model.add(Dropout(0.25)) ## To Avoid overfitting

In [145]:
model.add(Flatten())

In [146]:
model.add(Dense(units=1500,activation='relu'))

In [147]:
model.add(Dropout(0.4))

In [148]:
## output layer
# here 38 different class problem so we are neend to here 38 different outputs
# softmax neuron gives the probability of each class in each neurons
model.add(Dense(units=38,activation='softmax' ))

## Compiling the Model

In [149]:
## here we are dicrease the learning rate becase of minimize the loss function
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [150]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_60 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_61 (Conv2D)              │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_29 (MaxPooling2D) │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_62 (Conv2D)              │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_63 (Conv2D)              │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_30 (MaxPooling2D) │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_64 (Conv2D)              │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_65 (Conv2D)              │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_31 (MaxPooling2D) │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_66 (Conv2D)              │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_67 (Conv2D)              │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_32 (MaxPooling2D) │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_68 (Conv2D)              │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_69 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_33 (MaxPooling2D) │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_6 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

### Model Training

In [151]:
training_history=model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
  21/2197 ━━━━━━━━━━━━━━━━━━━━ 25:53 714ms/step - accuracy: 0.0346 - loss: 4.1779

KeyboardInterrupt: 

### Model evaluation

In [ ]:
## Model Evaluation on Training set
train_loss,train_acc=model.evaluate(training_set)

print(train_loss,train_acc)

In [ ]:
## Model on validation set
val_loss,val_acc=model.evaluate(validation_set)

print(val_loss,val_acc)

## Saving Model

In [ ]:
model.save("Trained_model.h5")

In [ ]:
model.save("Trained_model.keras")

In [ ]:
training_history.history

In [ ]:
## Recording history in json Formate
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)

In [ ]:
training_history.history['accuracy']

In [ ]:
training_history.history['val_accuracy']

### Accuracy Visualization

In [ ]:
epochs=[i for i in range(1,11)]
epochs

In [ ]:
plt.plot(epochs,training_history.history['accuracy'],color='Red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel("No. of Epochs")
plt.ylabel("Accuracy Result")
plt.title("Visualization of Accuracy Result.")
plt.legend()
plt.show()